name: aptabase_flutter
description: "Flutter SDK for Aptabase: Open Source Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps"
version: 0.1.2
homepage: https://aptabase.com
repository: https://github.com/aptabase/aptabase_flutter
issue_tracker: https://github.com/aptabase/aptabase_flutter/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0 #^11.1.0
  universal_io: ^2.2.0
  
  # if no connectivity persist data
  connectivity_plus: ^7.0.0 #4.0.2 #supports windows which is better than cross_connectivity
  internet_connection_checker_plus: ^2.5.2
  sembast: ^3.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
